Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -33,6 +33,14 @@ jobs:
             git stash
             git pull origin master
 
+            # طباعة سجل أخطاء Nginx
+            echo "Printing Nginx error logs"
+            sudo cat /var/log/nginx/error.log || echo "No Nginx error log found"
+
+            # طباعة سجل أخطاء PM2
+            echo "Printing PM2 error logs"
+            pm2 logs || echo "No PM2 logs found"
+
             # تثبيت Yarn و PM2 إذا لم يكونا مثبتين
             if ! command -v yarn &> /dev/null; then
               npm install -g yarn
@@ -48,6 +56,10 @@ jobs:
             # بناء التطبيق
             yarn build
 
+            # قتل كافة عمليات PM2 قبل إعادة التشغيل
+            echo "Killing all PM2 processes"
+            pm2 kill
+
             # إدارة العملية باستخدام PM2
             if pm2 list | grep -q "ve-frontend"; then
               pm2 restart ve-frontend
@@ -56,4 +68,6 @@ jobs:
             fi
 
             pm2 save  # حفظ العمليات في PM2 للبدء التلقائي
+
+            # إعادة تشغيل Nginx
             sudo systemctl restart nginx  # إعادة تشغيل Nginx
